{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: autoforge-secretstore
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoforge-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: autoforge-secretstore
    kind: SecretStore
  target:
    name: autoforge-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.secretsManagerKey }}
        property: password
    - secretKey: FLASK_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.secretsManagerKey }}
        property: flask_secret_key
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.secretsManagerKey }}
        property: admin_password
{{- end }}
